# This file must be named config.yaml and placed in the config/ directory

# Populate the scenarios.csv file with a list of scenario names
# and path (description optional) to the model csv data
scenarios: examples/3/scenarios.csv

# Tell the workflow which model results to plot
results: examples/3/results.csv

# Filetype options: 'csv' or 'parquet' or 'feather'
filetype: csv

# Define the uncertain parameters used to define the Monte Carlo sample
parameters: examples/3/parameters.csv

# Path to the OSeMOSYS model file
model_file: examples/3/osemosys.txt

# Choose a solver, choices: 'cbc' or 'gurobi' or 'cplex'
solver: cbc

# Sampling - how large should the sample be?
replicates: 5

# Scale Elementary Effects (True/False)
scale: False

# For large models, zip lp file and solution (True/False)
zip: True

